import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const domain='https://nivalisnights.wiki';
const date='2026-07-19';
const steam='https://store.steampowered.com/app/1488490/Nivalis_Nights/';
const officialFaq='https://steamcommunity.com/app/1488490/discussions/0/598530855994991183/';
const news='https://steamcommunity.com/app/1488490/allnews/';

const de=[
['first-person-perspective','Ist Nivalis Nights in der Ego-Perspektive?','Bestätigte Kameraperspektive, sichtbarer Körper und Gründe für das immersive Design.','Nivalis Nights wird aus der Ego-Perspektive gespielt. Laut offizieller FAQ ist diese Sicht bewusst gewählt, damit Spieler die Größe und Atmosphäre der Stadt unmittelbar erleben.',[['Was vom Spieler sichtbar ist','Es gibt keinen ständig sichtbaren Third-Person-Avatar. Die Spielfigur steht direkt im Mittelpunkt der Erfahrung; nach aktuellem Stand sind nur Arme und Hände des eigenen Körpers zu sehen.'],['Warum die Ego-Perspektive gewählt wurde','ION LANDS verbindet die Kamerawahl mit Immersion und dem enormen Maßstab von Nivalis. Eine umschaltbare Third-Person-Kamera oder ein separater Erkundungsmodus wurde nicht angekündigt.'],['Noch offene Komfortoptionen','Details zu Sichtfeldregler, Kamerawackeln und Einstellungen gegen Bewegungskrankheit sind noch nicht veröffentlicht. Diese Optionen werden erst anhand der finalen PC-Version dokumentiert.']]],
['character-customization','Kann man den eigenen Charakter anpassen?','Aktueller Status von Aussehen, Avatar und Charaktereditor in Nivalis Nights.','Nivalis Nights bietet derzeit keine optische Anpassung der Spielfigur. Die offizielle FAQ beschreibt keinen virtuellen Avatar; sichtbar sind lediglich Arme und Hände.',[['Kein Charaktereditor angekündigt','Es gibt keine bestätigte Auswahl für Gesicht, Körper, Haare, Kleidung oder andere äußerliche Merkmale. Die umfangreiche Anpassung von Wohnungen und Geschäften ist davon ein getrenntes System.'],['Gestaltung aus der Ich-Perspektive','Die Stadt wird direkt aus der Ego-Perspektive erlebt. Andere Bewohner verwenden detaillierte traditionelle Charaktermodelle, doch daraus folgt kein anpassbares Modell für den Spieler.'],['Was später geprüft werden muss','Die offizielle Aussage behandelt die visuelle Avatar-Anpassung. Ob Ärmel, Accessoires oder einzelne sichtbare Handdetails im Spiel wechseln können, ist noch nicht vollständig dokumentiert.']]],
['photo-mode','Hat Nivalis Nights einen Fotomodus?','Bestätigter Fotomodus und Funktionen, die erst in der Veröffentlichung geprüft werden können.','Ja, Nivalis Nights enthält einen offiziell bestätigten, eigenen Fotomodus für virtuelle Fotografie in der Cyberpunk-Stadt.',[['Bestätigter Bestandteil','Der Fotomodus gehört zum angekündigten Spielumfang und ist mehr als die normale Screenshot-Funktion von Steam. Spieler erhalten eine eigene Funktion zum Fotografieren der Stadt.'],['Werkzeuge noch nicht aufgelistet','Freie Kamera, Filter, Tiefenschärfe, Posen, Tageszeitsteuerung und das Ausblenden von Figuren oder Benutzeroberfläche wurden noch nicht einzeln bestätigt.'],['Plan für den fertigen Guide','Nach Release dokumentiert der Guide Aktivierung, Kameragrenzen, Effekte, Speicherort und die Frage, ob Fotomodus Zeitpläne, Wetter oder Geschäftsbetrieb pausiert.'],['Motive in der Stadt','Skyhigh Gardens, Calypso Island, die Docks und wetterabhängige Straßenszenen sind mögliche Motive. Konkrete Filter oder versteckte Fotoaufgaben werden erst aufgenommen, wenn sie im fertigen Spiel nachweisbar sind.']]],
['offline-play','Kann man Nivalis Nights offline spielen?','Internetpflicht, Plattform-Updates und Cloud-Speicherung verständlich erklärt.','Für das normale Einzelspieler-Erlebnis ist keine dauerhafte Internetverbindung erforderlich. Plattform-Updates und Cloud-Spielstände benötigen jedoch eine Verbindung.',[['Einzelspieler ohne Online-Sitzung','Die offizielle FAQ nennt Nivalis Nights ein reines Einzelspieler-Spiel; Mehrspieler und Koop sind nicht geplant. Das laufende Spiel hängt daher nicht von einer gemeinsamen Online-Sitzung ab.'],['Wann Internet trotzdem gebraucht wird','Steam oder Epic können für Installation, Aktualisierung, Kontoprüfung und Cloud-Synchronisierung eine Verbindung verlangen. Das ist nicht dasselbe wie eine Always-online-Pflicht während des Spielens.'],['Spielstände schützen','Wer mehrere Geräte verwendet, sollte die Cloud-Synchronisierung vor dem Wechsel vollständig abschließen. Konfliktbehandlung und Offline-Modus hängen auch vom jeweiligen Store-Client ab.']]],
['ultrawide-support','Unterstützt Nivalis Nights Ultrawide-Monitore?','Offizielle Ultrawide-Bestätigung sowie Informationen zu Seitenverhältnissen und Benutzeroberfläche.','Ja. Die offizielle FAQ bestätigt Ultrawide-Unterstützung; der Optimierungsbericht vom Mai 2026 beschreibt außerdem eine Benutzeroberfläche für verschiedene Seitenverhältnisse.',[['Ultrawide ist bestätigt','Die Entwickler beantworten die grundsätzliche Frage eindeutig. Genaue getestete Auflösungen, horizontales Sichtfeld und die Darstellung von Zwischensequenzen sind noch nicht veröffentlicht.'],['Mehr als 40 Oberflächenelemente','Fenster, Panels und weitere UI-Elemente wurden für unterschiedliche Bildformate optimiert. Der Entwicklungsbericht erwähnt ausdrücklich auch eine Darstellung im Seitenverhältnis 4:3.'],['Saubere Kompatibilitätstests','21:9 und 32:9 sollten getrennt in Spielwelt, Menüs, Untertiteln, Fotomodus und Zwischensequenzen geprüft werden. Ein funktionierender Bildschirm allein beweist keine vollständige Unterstützung.'],['Leistung getrennt bewerten','Eine richtig skalierte Oberfläche garantiert keine identische Bildrate auf breiteren Auflösungen. Tests dokumentieren Seitenverhältnis, Auflösung, Sichtfeld, GPU-Auslastung und schwarze Balken deshalb als getrennte Messpunkte.']]],
['vr-support','Unterstützt Nivalis Nights VR?','Aktueller offizieller VR-Status und Unterschied zwischen Ego-Perspektive und Virtual Reality.','VR-Unterstützung ist derzeit nicht geplant und hat laut offizieller FAQ keine Entwicklungspriorität.',[['Ego-Perspektive ist nicht automatisch VR','Eine Kamera aus der Ich-Perspektive bietet noch kein Headset-Tracking, keine Bewegungssteuerung, kein stereoskopisches Rendering und keine für VR angepasste Benutzeroberfläche.'],['Keine Headsets bestätigt','Es gibt keine offizielle Unterstützungsliste für Meta Quest, Valve Index, HTC Vive, PlayStation VR2 oder andere PC-VR-Systeme.'],['Status kann nur offiziell geändert werden','Die Aussage beschreibt den aktuellen Umfang. Diese Seite wird erst angepasst, wenn ION LANDS oder 505 Games konkrete VR-Hardware und eine unterstützte Version ankündigt.'],['Keine inoffizielle Kompatibilität versprechen','Desktop-Streaming in ein Headset oder externe Kamera-Modifikationen sind keine native VR-Unterstützung. Solche Umwege dürfen nicht als bestätigte Bewegungssteuerung oder komfortables VR-Erlebnis bezeichnet werden.']]],
['mod-support','Unterstützt Nivalis Nights Mods?','Status offizieller Modding-Werkzeuge, Steam Workshop und vorsichtige Erwartungen vor Release.','Offizielle Modding-Werkzeuge gehören derzeit nicht zum Umfang von Nivalis Nights. Steam-Workshop-Unterstützung ist auf der Store-Seite ebenfalls nicht aufgeführt.',[['Kein offizielles Toolkit','ION LANDS erklärt, dass Modding-Tools momentan nicht Teil des Projekts sind. Die Unity-Technik und die voxelartige Umgebung sind weder Dokumentation noch Freigabe für Modifikationen.'],['Workshop nicht als Steam-Funktion genannt','Steam listet Erfolge, Cloud-Speicherung und Familienbibliothek, aber keine Workshop-Integration. Deshalb darf ein späterer Workshop nicht vorab versprochen werden.'],['Keine ungesicherten Anleitungen','Dateiformate, Skriptzugriff und Savegame-Änderungen lassen sich vor Veröffentlichung nicht seriös beschreiben. Künftige Inhalte müssen offiziellen Support von inoffiziellen Experimenten unterscheiden.']]],
['camus-return','Kehrt Camus aus Cloudpunk zurück?','Offizieller Status von Camus und Verbindungen zwischen Cloudpunk und Nivalis Nights.','Derzeit gibt es keine Pläne, Camus in Nivalis Nights zurückzubringen. Beide Spiele teilen sich die Stadt, aber das neue Spiel konzentriert sich auf neue Menschen und eine eigenständige Handlung.',[['Direkte offizielle Antwort','Die angeheftete FAQ sagt, dass ein Besuch von Camus aktuell nicht geplant ist. Daraus darf kein angeblicher geheimer Auftritt, keine Quest und kein Sammelobjekt konstruiert werden.'],['Bekannte Stadt, neue Erfahrung','Cloudpunk-Spieler können vertraute Details und kleine Verbindungen entdecken. Vorwissen ist trotzdem nicht notwendig, weil Nivalis Nights als eigenständiges Erlebnis gestaltet wird.'],['Bestätigte Figuren statt Spekulation','Salt Pete ist ein offiziell vorgestellter Bewohner; insgesamt gibt es mehr als 130 geschriebene Charaktere. Eine eigene Seite setzt einen bestätigten Namen und nützliche Details voraus.']]],
['printed-meat','Kann man in Nivalis Nights Fleisch drucken?','Wie gedrucktes Fleisch mit Gewächshaus, Zutaten und Restaurantversorgung verbunden ist.','Ja. Der offizielle Gewächshaus-Bericht bestätigt, dass spezialisierte Maschinen Fleisch drucken können, während Spieler außerdem Pilze, Getreide und Gemüse anbauen.',[['Teil der Hightech-Landwirtschaft','Gedrucktes Fleisch gehört zum Gewächshaussystem und nicht zu einer bestätigten Viehzucht. Gemietete Räume werden mit spezialisierten Maschinen verschiedener Händler ausgestattet.'],['Versorgung der Restaurants','Produzierte Zutaten können verkauft oder an eigene Restaurants geliefert werden. Namen, Rezepte, Ausgabemengen und Gewinnspannen des gedruckten Fleisches sind noch nicht öffentlich aufgelistet.'],['Keine erfundenen Varianten','Diese Seite dokumentiert nur die bestätigte Produktionsmethode. Rind, Geflügel oder andere Sorten erhalten erst dann eigene Einträge, wenn offizielle Namen und konkrete Verwendung bekannt sind.']]],
['furniture-item-count','Wie viele Möbel gibt es in Nivalis Nights?','Bestätigte Möbelanzahl, Händlersortimente und Qualitätsregeln für die Datenbank.','ION LANDS nennt 620 Möbelgegenstände. Sie können in Wohnungen, Geschäftsräumen und bezahlten Innenarchitektur-Aufträgen eingesetzt werden.',[['Bestätigte Gesamtzahl','Der Optimierungsbericht vom Mai 2026 nennt 620 Möbel im Zusammenhang mit mehr als 40 Fenstern und Panels, die große Inhaltsmengen übersichtlich darstellen müssen.'],['Beschaffung und Gestaltung','Verschiedene Händler führen eigene Möbel und Accessoires. Sets unterscheiden sich durch Materialien und erzeugen unterschiedliche Atmosphären in Wohnungen und Betrieben.'],['Wann ein Gegenstand eine Seite erhält','Die Gesamtzahl ist keine Namensliste. Einzelne URLs benötigen einen bestätigten Gegenstandsnamen, Händler oder Freischaltung, Preis und konkrete Informationen zur Platzierung.']]],
['voiced-characters','Wie viele Figuren in Nivalis Nights sind vertont?','Aktueller offizieller Umfang der Sprachausgabe, Sprachabdeckung und Besetzungsstatus.','Ein Entwicklungsbericht vom Januar 2026 nennt mehr als 135 Haupt- und Nebenfiguren, für die Sprachausgabe implementiert wurde.',[['Umfang der Produktion','Im September 2025 wurden mehr als 6.000 Bewerbungen geprüft. Der spätere Januar-Bericht beschreibt die laufende Vertonung von über 135 Figuren.'],['Verfügbare Audiosprache','Steam markiert nur Englisch mit vollständiger Sprachausgabe. Zehn weitere Sprachen, darunter Deutsch und Japanisch, werden für Oberfläche und Untertitel angeboten.'],['Noch nicht veröffentlichte Angaben','Die vollständige Besetzung, Anzahl der gesprochenen Zeilen und Vertonung jedes optionalen NPCs sind nicht bekannt. Namen von Sprechern werden nur mit offizieller Quelle ergänzt.']]],
['demo-status','Gibt es eine Nivalis-Nights-Demo?','Aktueller Status von Demo, spielbarer Vorschau und Early Access anhand offizieller Quellen.','Derzeit ist keine öffentliche Nivalis-Nights-Demo verfügbar oder auf Steam gelistet. Das Spiel soll als Vollversion und nicht im Early Access erscheinen.',[['Aktueller Store-Status','Steam bietet Wunschliste und Release-Benachrichtigung, aber keinen Button zum Herunterladen einer Demo. Trailer, Showcase-Auftritte und das Video zum frühen Spielablauf sind keine spielbare Demo.'],['Kein Early Access','Die offizielle angeheftete FAQ bestätigt einen Start als Vollversion ohne Early-Access-Phase. Das beweist nicht, dass niemals eine zeitlich begrenzte Vorschau erscheint; aktuell ist jedoch keine angekündigt.'],['Verlässliche Aktualisierung','Der Status wird gegen Store und offizielle Meldungen geprüft. Wünsche aus der Community, Gerüchte oder unbeantwortete Diskussionsbeiträge gelten nicht als Bestätigung.']]]
];

const ja=[
['first-person-perspective','Nivalis Nightsは一人称視点？','公式に確認されたカメラ視点、見える身体、没入感を重視した設計を解説します。','Nivalis Nightsは一人称視点でプレイします。公式FAQでは、街の巨大さと空気感を直接体験させるための意図的な選択だと説明されています。',[['プレイヤーから見えるもの','常に表示される三人称アバターはありません。プレイヤー自身が体験の中心に置かれ、現在公式に見えると説明されている身体部分は腕と手だけです。'],['一人称を選んだ理由','ION LANDSは、Nivalisの規模を感じさせる没入感とカメラ視点を結び付けています。三人称への切り替えや別の探索カメラは発表されていません。'],['今後確認する設定','視野角、カメラ揺れ、乗り物酔い対策などの詳細設定は未公開です。ほかの一人称ゲームから推測せず、製品版のPC設定で確認します。']]],
['character-customization','主人公の見た目を変更できる？','キャラクター作成、アバター表示、外見カスタマイズの現在の公式状況です。','Nivalis Nightsには現在、主人公の外見を変更する機能はありません。公式FAQでは仮想アバターを使わず、腕と手だけが見えると説明されています。',[['外見作成は未発表','顔、体格、髪型、服装などを選ぶキャラクタークリエイターは確認されていません。住宅や店舗の豊富な装飾機能とは別の問題です。'],['一人称で街を体験','プレイヤーは一人称で直接街に入ります。住民には表情豊かな通常の3Dキャラクターメッシュが使われますが、主人公モデルを編集できる根拠にはなりません。'],['残る確認項目','公式回答は外見アバターのカスタマイズについてです。袖、装飾品、手の見た目などが進行によって変化するかは、まだ完全には説明されていません。'],['カスタマイズできる別の要素','主人公の外見編集はなくても、住宅、店舗、家具、温室、レシピなどには選択や調整があります。検索時にはキャラクター作成と生活空間の装飾を混同しないことが重要です。']]],
['photo-mode','Nivalis Nightsにフォトモードはある？','確認済みのフォトモードと、製品版で確認すべき撮影機能を整理します。','はい。公式Nivalis Nights FAQは、バーチャル写真撮影のためのフォトモードを明確に確認しています。',[['公式に確認済み','フォトモードは発表済みのゲーム機能です。Steamの通常スクリーンショットとは異なり、ゲーム内に専用の撮影機能が用意されます。'],['詳細ツールは未公開','自由カメラ、フィルター、被写界深度、ポーズ、時間変更、NPCやUIの非表示などは個別に公開されていません。'],['発売後の検証内容','起動方法、カメラ移動範囲、効果、保存先に加え、撮影中にNPCの予定、天候、店舗運営が停止するかを製品版で確認します。'],['撮影候補となる場所','Skyhigh Gardens、Calypso Island、港、雨や雪の街路は公式映像から有力な撮影候補です。ただし、撮影クエストや専用報酬があるとは発表されていません。']]],
['offline-play','Nivalis Nightsはオフラインで遊べる？','インターネット接続、ストア更新、Steam Cloudの違いを説明します。','通常プレイに常時インターネット接続は必要ありません。ただし、プラットフォーム更新とクラウドセーブには接続が必要です。',[['一人用ゲームとして設計','公式FAQではシングルプレイ作品とされ、マルチプレイや協力プレイは予定されていません。ゲーム進行は他のプレイヤーとのオンラインセッションを前提にしていません。'],['接続が必要になる場面','SteamやEpicでは、導入、アップデート、アカウント確認、クラウド同期に通信を使う場合があります。これはプレイ中の常時接続条件とは異なります。'],['セーブデータの注意','複数PCを使う場合は、別端末へ移る前にクラウド同期を完了させる必要があります。競合処理やオフラインモードは各ストアクライアントにも依存します。']]],
['ultrawide-support','ウルトラワイドモニターに対応する？','公式のウルトラワイド対応と画面比率、UI最適化の状況です。','はい。公式FAQはウルトラワイド対応を確認しており、2026年5月の最適化記事では複数の画面比率を想定したUI設計も説明されています。',[['ウルトラワイド対応は確定','基本的な対応には明確な回答があります。ただし、検証済み解像度、横方向の視野角、カットシーン表示の詳細はまだ公開されていません。'],['40以上のUI要素','40を超えるウィンドウ、パネル、インターフェース要素が各種画面に合わせて調整されています。同じ記事では4:3表示への対応も明記されています。'],['製品版で分けて検証','21:9と32:9について、通常プレイ、メニュー、字幕、フォトモード、カットシーンを別々に確認します。一画面が表示されるだけでは完全対応とは判断しません。']]],
['vr-support','Nivalis NightsはVRに対応する？','公式VR対応状況と、一人称視点と仮想現実の違いを整理します。','VR対応は現在の計画になく、公式FAQでは開発上の優先事項でもないと説明されています。',[['一人称視点とVRは別','一人称カメラだけでは、ヘッドセット追跡、モーション操作、左右眼の立体描画、VR向けUIは実現しません。'],['対応機器は未発表','Meta Quest、Valve Index、HTC Vive、PlayStation VR2など、公式に対応すると発表されたヘッドセットはありません。'],['将来の扱い','回答は現在の開発範囲を示しています。ION LANDSまたは505 Gamesが具体的な機器と対応版を発表した場合にのみ、このページを更新します。'],['非公式な表示との違い','ヘッドセット内に通常のPC画面を映す機能や外部ツールは、ネイティブVR対応ではありません。公式な追跡、操作、快適性が確認されるまではVR版として案内しません。']]],
['mod-support','Nivalis NightsはModに対応する？','公式Modツール、Steam Workshop、発売前に断定できない内容を解説します。','公式Mod制作ツールは現在のNivalis Nightsの開発範囲に含まれていません。SteamストアにもWorkshop対応は記載されていません。',[['公式ツールは未発表','ION LANDSは、Modツールは現時点のゲーム範囲外だと回答しています。Unity製であることやボクセル風の街は、改造方法や公式許可を意味しません。'],['Workshop表示もない','Steamの機能欄には実績、Steam Cloud、ファミリーシェアがありますが、Steam Workshopはありません。将来の導入を先に約束することはできません。'],['未確認の改造情報を掲載しない','ファイル形式、スクリプト、セーブ編集は発売前に安全かつ正確に説明できません。将来の記事では公式対応と非公式な実験を明確に分けます。']]],
['camus-return','CloudpunkのCamusは登場する？','Camusの公式状況とCloudpunkとのつながりを解説します。','現在、CamusをNivalis Nightsに再登場させる計画はありません。同じ街を舞台にしますが、本作は新しい住民と独立した物語を中心にしています。',[['公式FAQの回答','公式の固定FAQでは、CamusがNivalisを訪れる予定は現在ないとされています。隠し登場、クエスト、収集物があると推測で書くべきではありません。'],['同じ都市、別の体験','Cloudpunkを遊んだ人は、見覚えのある場所や小さなつながりに気付く可能性があります。ただし本作は単独で楽しめるよう設計されています。'],['確認された人物を優先','Salt Peteは公式に紹介された住民で、作り込まれた登場人物は130人を超えます。個別ページには正式名と役割を含む十分な根拠が必要です。']]],
['printed-meat','温室で肉をプリントできる？','プリント肉と温室、食材、レストラン供給の関係を解説します。','はい。公式の温室開発記事では、キノコ、穀物、野菜の栽培に加え、専門機械で肉をプリントできると説明されています。',[['ハイテク農業の一部','プリント肉は温室システムの機能であり、家畜飼育が確認されたわけではありません。借りた温室へ、専門業者から購入した機械を配置します。'],['店舗への供給','生産した食材は販売するか、自分のレストランへ送れます。プリント肉の正式名、レシピ、生産量、利益率はまだ公開されていません。'],['存在しない種類を作らない','確認済みの生産方法だけを記録します。牛肉、鶏肉などの個別ページは、正式なゲーム内名称と用途が確認されるまで作成しません。'],['利益計算で必要な情報','製品版では機械価格、必要電力や資材、処理時間、完成量、販売価格、料理での消費量を同じ条件で記録します。数値がない発売前段階で最強食材とは断定しません。']]],
['furniture-item-count','家具は何種類ある？','確認済み家具数、販売業者、データベース掲載基準をまとめます。','ION LANDSは家具アイテムが620個あると報告しています。住宅、店舗、有料インテリア依頼で使用できます。',[['確認された総数','2026年5月の最適化記事では、40以上のUI画面が大量のデータを扱う説明の中で620個の家具が挙げられています。'],['家具の入手と雰囲気','街の異なる業者が独自の家具とアクセサリーを販売します。セットは素材によって雰囲気が変わり、住宅と店舗の両方に配置できます。'],['個別URLを作る条件','620という数字は名称一覧ではありません。個別ページには正式名、販売店または解放方法、価格、配置に関する具体的情報が必要です。'],['装飾依頼との関係','自宅では好みを優先できますが、有料の依頼では顧客の指示、趣味、必須条件を満たす必要があります。同じ家具でも入手場所と依頼での役割を分けて記録します。']]],
['voiced-characters','何人のキャラクターに音声がある？','最新の公式ボイス規模、対応言語、声優情報の公開状況です。','2026年1月の開発記事では、主要人物と脇役を合わせた135人以上にボイスを実装していると報告されています。',[['音声制作の規模','2025年9月には6,000件を超えるオーディションを審査中と報告され、その後の1月記事で135人以上への音声実装が説明されました。'],['フル音声の言語','Steamでフル音声にチェックがあるのは英語だけです。日本語とドイツ語を含むほか10言語は、インターフェースと字幕に対応します。'],['まだ公開されていない情報','完全な声優一覧、台詞数、任意NPCすべてがフルボイスかどうかは未発表です。公式クレジットなしで声優名を割り当てません。'],['日本語字幕で確認する点','日本語版はインターフェースと字幕に対応予定ですが、日本語フル音声は確認されていません。字幕速度、固有名詞、会話ログ、英語音声との同期も発売後に検証します。']]],
['demo-status','Nivalis Nightsの体験版はある？','Steam体験版、プレイ可能なプレビュー、早期アクセスの最新状況です。','現在、一般公開されたNivalis Nights体験版はなく、Steamストアにも掲載されていません。本作は早期アクセスではなく製品版として発売予定です。',[['現在のSteam表示','ストアにはウィッシュリストと発売通知がありますが、体験版ダウンロードボタンはありません。紹介映像や序盤プレビュー動画は、操作できる公開体験版ではありません。'],['早期アクセスなし','公式の固定FAQは、早期アクセス期間を設けず製品版として発売すると明記しています。将来の限定試遊を完全に否定する意味ではありませんが、現在は発表されていません。'],['情報更新の基準','体験版の有無はSteamストアと公式発表で確認します。コミュニティの要望、噂、返答のない投稿は公式確認として扱いません。']]]
];

const baseSlugs=['','guides','faq','release-date','system-requirements','gameplay-systems','businesses','restaurant-management','greenhouses','fishing-guide','transportation','locations','skyhigh-gardens','apartment-decorating','characters','relationships','story','platforms'];
const translatedSlugs=new Set([...baseSlugs,...de.map(p=>p[0])]);
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const alt=slug=>{const tail=slug?`${slug}/`:'';return `<link rel="alternate" hreflang="en" href="${domain}/${tail}"><link rel="alternate" hreflang="de" href="${domain}/de/${tail}"><link rel="alternate" hreflang="ja" href="${domain}/ja/${tail}"><link rel="alternate" hreflang="x-default" href="${domain}/${tail}">`;};
function render(lang,p){
 const [slug,title,description,answer,sections]=p;const isDe=lang==='de';const url=`${domain}/${lang}/${slug}/`;
 const schema=JSON.stringify({'@context':'https://schema.org','@type':'Article',inLanguage:lang,headline:title,description,mainEntityOfPage:url,datePublished:date,dateModified:date,author:{'@type':'Organization',name:'Nivalis Nights Wiki'}});
 const sectionHtml=sections.map(([h,b])=>`<section class="panel"><h2>${esc(h)}</h2><p>${esc(b)}</p></section>`).join('');
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Nivalis Nights Wiki</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}">${alt(slug)}<meta property="og:type" content="article"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:locale" content="${isDe?'de_DE':'ja_JP'}"><meta property="og:image" content="https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1488490/header.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${schema}</script></head><body><header class="top"><nav class="nav wrap" aria-label="${isDe?'Navigation':'ナビゲーション'}"><a href="/${lang}/">Nivalis Nights Wiki</a><a href="/${lang}/guides/">${isDe?'Guides':'攻略'}</a><a href="/${lang}/businesses/">${isDe?'Unternehmen':'店舗'}</a><a href="/${lang}/characters/">${isDe?'Charaktere':'人物'}</a><a href="/${lang}/faq/">FAQ</a></nav></header><main class="wrap"><div class="crumb"><a href="/${lang}/">${isDe?'Startseite':'ホーム'}</a> / ${esc(title)}</div><h1>${esc(title)}</h1><p class="lede">${esc(description)}</p><div class="answer"><strong>${isDe?'Kurzantwort:':'要点：'}</strong> ${esc(answer)}</div>${sectionHtml}<section><h2>${isDe?'Verwandte Guides':'関連ガイド'}</h2><div class="cards"><a class="card" href="/${lang}/guides/"><strong>${isDe?'Alle Guides':'攻略一覧'}</strong><span>Nivalis Nights</span></a><a class="card" href="/${lang}/characters/"><strong>${isDe?'Charaktere':'キャラクター'}</strong><span>Nivalis Nights</span></a><a class="card" href="/${lang}/faq/"><strong>FAQ</strong><span>Nivalis Nights</span></a></div></section><section class="panel source"><h2>${isDe?'Quellen und Prüfung':'出典と確認'}</h2><p>${isDe?'Diese Seite basiert auf offiziellen Angaben und kennzeichnet nicht veröffentlichte Details klar.':'このページは公式情報を基準にし、未発表の内容を明確に区別しています。'} <a href="${steam}" rel="nofollow">Steam</a> · <a href="${officialFaq}" rel="nofollow">FAQ</a> · <a href="${news}" rel="nofollow">News</a></p></section><p class="updated">${isDe?'Zuletzt geprüft: 19. Juli 2026':'最終確認：2026年7月19日'} · Independent, unofficial player guide.</p></main><footer class="footer"><div class="wrap">Nivalis Nights Wiki · Independent fan resource</div></footer></body></html>`;
}

for(const [lang,pages] of [['de',de],['ja',ja]])for(const p of pages){const dir=path.join(root,lang,p[0]);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),render(lang,p));}

for(const slug of de.map(p=>p[0])){const file=path.join(root,slug,'index.html');let html=fs.readFileSync(file,'utf8');html=html.replace(/<link rel="alternate" hreflang="(?:en|de|ja|x-default)"[^>]*>/g,'');html=html.replace('</head>',`${alt(slug)}</head>`);fs.writeFileSync(file,html);}

let sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');const existing=new Set([...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]));const extra=[];
for(const lang of ['de','ja'])for(const slug of de.map(p=>p[0])){const url=`${domain}/${lang}/${slug}/`;if(!existing.has(url))extra.push(`  <url><loc>${url}</loc><lastmod>${date}</lastmod></url>`);}
if(extra.length)sitemap=sitemap.replace('\n</urlset>',`\n${extra.join('\n')}\n</urlset>`);fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);

const htmlFiles=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git'].includes(e.name))continue;const p=path.join(dir,e.name);e.isDirectory()?walk(p):e.name.endsWith('.html')&&htmlFiles.push(p)}}walk(root);
for(const file of htmlFiles){let html=fs.readFileSync(file,'utf8');if(!/<nav class="nav wrap"/.test(html))continue;const rel=path.relative(root,file).replaceAll(path.sep,'/');let route=rel==='index.html'?'':rel.replace(/\/index\.html$/,'');let current='en';if(route==='de'||route.startsWith('de/')){current='de';route=route.replace(/^de\/?/,'')}else if(route==='ja'||route.startsWith('ja/')){current='ja';route=route.replace(/^ja\/?/,'')};const slug=route;const hasTranslation=translatedSlugs.has(slug);const en=slug?`/${slug}/`:'/';const deUrl=hasTranslation?(slug?`/de/${slug}/`:'/de/'):'/de/';const jaUrl=hasTranslation?(slug?`/ja/${slug}/`:'/ja/'):'/ja/';const labels={en:'English',de:'Deutsch',ja:'日本語'};const menu=`<details class="language-menu"><summary aria-label="Choose language">${labels[current]}</summary><div class="language-options"><a href="${en}" hreflang="en" lang="en">English</a><a href="${deUrl}" hreflang="de" lang="de">Deutsch</a><a href="${jaUrl}" hreflang="ja" lang="ja">日本語</a></div></details>`;html=html.replace(/<details class="language-menu">[\s\S]*?<\/details>/g,'').replace(/<a href="[^"]*">(?:English|Deutsch|日本語)<\/a>/g,'');html=html.replace(/(<nav class="nav wrap"[\s\S]*?)(<\/nav>)/,`$1${menu}$2`);fs.writeFileSync(file,html);}
console.log(`Added ${de.length} German and ${ja.length} Japanese current-data pages and dropdown language navigation across ${htmlFiles.length} HTML files.`);
