import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const domain='https://nivalisnights.wiki';
const updated='2026-07-17';
const steam='https://store.steampowered.com/app/1488490/Nivalis_Nights/';
const devlog='https://steamcommunity.com/app/1488490';

const pages=[
  ['guides','Nivalis Nights Guides','Browse confirmed pre-release guides for release details, PC requirements, businesses, fishing, relationships, apartments, boats, curfew and more.','The guide library separates confirmed information from details that still require the final game. Start with release and platform answers, then explore each officially announced gameplay system.',[
    ['What you can research now','Nivalis Nights has a confirmed Steam release date and a detailed official feature list. That supports useful pages about PC requirements, controller input, businesses, ingredients, meals, fishing, boating, homes, relationships, chess, curfew and sabotage. Each guide below answers only what the developers or storefront currently confirm.'],
    ['How the library will grow','At launch, broad guides will connect to exact quest walkthroughs, named character schedules, recipes, ingredients, furniture, fish and locations. New leaf pages will be indexed only after they contain a concrete answer, source or tested in-game evidence rather than a copied placeholder.']]],
  ['databases','Nivalis Nights Database','Database hubs for the 100+ quests, 240+ ingredients, 190 meals and 620 furniture items disclosed by the Nivalis Nights developers.','The developers have publicly quantified four large content systems: more than 100 quests, over 240 ingredients, 190 meals and 620 furniture items. These hubs are ready to receive verified entries without publishing empty leaf pages.',[
    ['Confirmed database scale','The May 2026 development update says the user interface must handle over 240 ingredients, 190 meals, 100 quests and 620 furniture items. Together, those four systems can support more than 1,150 useful entity pages once names, values, requirements and locations are verified.'],
    ['Indexing rule','A category count is not permission to fabricate URLs. Every entity page needs its exact name plus useful attributes: where to obtain it, what it does, prerequisites, costs or rewards, and genuinely related entries. Until those data exist, only the database hubs belong in the sitemap.']]],
  ['quests','Nivalis Nights Quests','What is confirmed about Nivalis Nights quests, story progression, choices and the planned walkthrough database.','Nivalis Nights contains more than 100 quests according to the developer optimization update. Exact quest names and steps are not yet public, so this hub explains the verified scope without inventing walkthroughs.',[
    ['How quests connect to the game','ION LANDS says major story beats link with gameplay systems and give rewards. The team has balanced quest difficulty, the economy and story pacing together, and says player choices are intended to feel meaningful. QA testing specifically covers quests and story progression.'],
    ['Walkthrough quality standard','After release, each quest page will open with the objective and prerequisites, followed by exact steps, locations, decisions, rewards and known trigger problems. Choice consequences will use spoiler labels. A quest name alone, a generic summary or an unverified objective will not pass the publication gate.']]],
  ['ingredients','Nivalis Nights Ingredients','Confirmed ingredient systems in Nivalis Nights, including buying, growing and the planned 240+ ingredient database.','The official Steam page says players can buy or grow their own ingredients, while the developer reports more than 240 ingredients in the game. Exact ingredient entries will be added after verification.',[
    ['What ingredients are for','Ingredients sit between resource gathering and business management. Official materials connect them to restaurants, noodle stands and ramen bars, while the Steam tags also identify cooking, inventory management and resource management as major themes.'],
    ['What each entry must answer','A useful ingredient page needs acquisition method, shop or growing source, cost, availability, recipe uses and any business value. Variants will not be split into separate URLs unless they have meaningfully different sources or uses.']]],
  ['meals','Nivalis Nights Meals and Recipes','What is known about the 190 meals in Nivalis Nights and how the recipe database will be built after release.','The May 2026 developer update confirms 190 meals. The final database will connect every verified meal to ingredients, preparation requirements and the businesses where it matters.',[
    ['Meals and the economy','Food is central to the announced business ladder: the player begins with a noodle stand and can progress through ramen bars, restaurants and other venues. A developer example also describes staff serving Nigiri to customers across the city, confirming that meals participate in persistent business simulation.'],
    ['Recipe page standard','Every meal page must provide a real recipe or unlock method, required ingredients, preparation station, sell price or business role, and related meals. Pages will not be generated from the number 190 alone.']]],
  ['furniture','Nivalis Nights Furniture','Furniture database plan for the 620 items confirmed by ION LANDS, plus home decoration and persistent world-state details.','ION LANDS reports 620 furniture items and says players can decorate their own homes or customize homes for friends. Individual pages will publish only when item details are known.',[
    ['Why furniture has search value','Furniture is not merely a marketing bullet. The developer describes polishing furniture assets for memory efficiency and says the persistent world system remembers more than 10,000 objects such as tables, chairs and dishes. This supports deep collection, placement and home-design guides after release.'],
    ['Furniture entry requirements','Each page should identify the exact item, acquisition source, price or unlock condition, category, placement limits and visual variants. Closely related cosmetic variants should remain on one page when separating them would create thin content.']]],
  ['characters','Nivalis Nights Characters and Relationships','Confirmed information about NPCs, friendships, rivals, romance and the future character guide database.','Nivalis Nights features a large cast with persistent daily schedules. Players can form friendships, make enemies, manage relationships and potentially find love.',[
    ['A city with persistent inhabitants','The developer says thousands of NPCs continue living their lives across districts. A three-tier “Ghost system” tracks out-of-district schedules, nearby unseen characters and fully visible NPCs differently to preserve performance. Not every simulated citizen will justify a search page; named characters with quests, relationships or services will.'],
    ['Character page standard','A character guide needs an exact name, role, locations or schedule, relationship mechanics, connected quests and verified choices. Romance status, gifts and event triggers must come from official information or play testing.']]],
  ['fish','Nivalis Nights Fish Database','How fishing works in Nivalis Nights and the evidence required for future fish location, bait and catch pages.','Fishing is a simulated system rather than a random roll: fish exist physically in the water, move in shoals and can follow other fish or the player’s bait.',[
    ['What the developer confirmed','ION LANDS says more than 1,000 fish can be simulated at once. The fish visible before a catch is the same entity the player catches. Fish also emit a warm glow, with the lighting rendered at reduced resolution to control GPU cost.'],
    ['Future fish guides','Individual pages will document verified species, water location, time or weather conditions, bait behavior, uses and value. No fish names or rarity claims will be published from screenshots alone unless identification is reliable.']]],
  ['businesses','Nivalis Nights Businesses','Business database hub covering noodle stands, ramen bars, restaurants, nightclubs, staff, ingredients and rival sabotage.','Business growth is a central progression path. The official description begins with a noodle stand and expands to restaurants and premier nightclubs.',[
    ['Confirmed business loop','Players choose whether to spend each day growing businesses or building relationships. They can buy or grow ingredients, operate food venues and nightlife businesses, and compete with rivals. The world simulation can continue tracking staff activity even when the player is elsewhere.'],
    ['What business pages will measure','After launch, each venue guide should cover unlock requirements, setup cost, products or meals, staffing, customer flow, upgrades, operating schedule and profit. Strategy pages need tested comparisons rather than assumed “best business” rankings.']]],
  ['locations','Nivalis Nights Locations and Districts','Location guide hub for the cyberpunk city, docks, districts, businesses, homes and future maps.','Nivalis stretches from the ocean to the clouds. Confirmed spaces include city districts, docks, homes, business venues and waters explored by boat.',[
    ['District simulation','The developer’s performance system distinguishes NPCs outside the player’s district, unseen NPCs in the current district and visible characters. That confirms districts are a meaningful world structure, but official materials do not yet provide a complete public district list.'],
    ['Location page standard','A location page must offer a map position or clear route, services, characters, quests, opening conditions and nearby landmarks. Screenshot galleries without navigation value will not be indexed as standalone location guides.']]],
  ['minigames','Nivalis Nights Minigames','Confirmed minigames in Nivalis Nights, including NPC challenges and the high-stakes cyberpunk chess tournament.','The Steam feature list confirms that players can challenge NPCs to minigames and take part in a chess tournament. Additional minigames will be documented only after confirmation.',[
    ['How minigames fit','Minigames provide activities outside business management, fishing and relationships. The official description specifically highlights a high-stakes cyberpunk chess tournament, suggesting at least one longer competitive activity rather than only disposable side interactions.'],
    ['Guide standard','Every minigame page should explain where it starts, its rules, opponents, entry requirements, rewards and progression. Difficulty advice must be based on the shipped rules.']]],
  ['restaurant-management','Nivalis Nights Restaurant Management','What is confirmed about owning and managing restaurants in Nivalis Nights, with launch-day data points to evaluate.','Players can work up from a humble noodle stand to owning top restaurants. Ingredients, meals, staff activity and the wider economy all connect to restaurant management.',[
    ['Confirmed progression','Official copy places restaurants between the starter noodle stand and the broader ambition of owning the city’s nightlife. The UI must support hundreds of ingredients and meals, while the persistent simulation can track staff serving food across the city.'],
    ['Launch strategy questions','The useful questions after release are concrete: which venue unlocks first, what it costs, which meals have strong margins, how staffing works and which upgrades remove bottlenecks. Until values are tested, there is no evidence for a definitive best restaurant route.']]],
  ['ramen-bar-guide','Nivalis Nights Ramen Bar Guide','How ramen bars fit the confirmed Nivalis Nights business system and what a complete management guide will cover.','Ramen bars are explicitly listed among the businesses players can manage. They connect the ingredient, meal, staffing and daily time-management systems.',[
    ['Ramen bars in the business ladder','The official description distinguishes noodle stands, busy ramen bars and larger restaurants or nightclubs. This implies multiple venue types, but exact upgrade paths, menus and profitability are not yet publicly documented.'],
    ['What to verify at launch','A complete ramen guide will test the unlock quest, purchase or setup cost, available recipes, ingredient supply, staff roles, customer capacity, hours and upgrades. It will compare profit only after using consistent operating periods.']]],
  ['nightclub-guide','Nivalis Nights Nightclub Guide','Confirmed nightclub management features and the questions to test when Nivalis Nights releases.','Nightclubs are a stated end point of the player’s climb through the Nivalis business scene. Official materials call them premier venues and part of owning the city’s nightlife.',[
    ['Beyond food businesses','Nightclubs broaden the management loop beyond stands and restaurants. The public description confirms nightclub ownership, competitors and curfew-era danger, but does not yet expose venue names, staffing requirements or entertainment systems.'],
    ['Launch guide scope','The finished guide will cover acquisition, operating costs, staff, stock, capacity, security, upgrades, reputation and profit. Any claim that a nightclub is the fastest money method must be supported by comparable in-game tests.']]],
  ['growing-ingredients','How to Grow Ingredients in Nivalis Nights','What the official material confirms about growing ingredients and how farming connects to cooking and businesses.','Players can legally grow their own ingredients instead of relying only on purchases. More than 240 ingredients exist across the game’s wider food and inventory systems.',[
    ['Why growing matters','Growing ingredients may provide supply for noodle stands, ramen bars and restaurants. The Steam page confirms the activity but does not yet specify plots, tools, growth times, seasons or whether every ingredient can be cultivated.'],
    ['What the launch guide will test','The first verified version should explain how growing unlocks, where it happens, required equipment, planting and harvest timing, yield, weather effects and the opportunity cost versus buying stock.']]],
  ['boat-guide','Nivalis Nights Boat Guide','Confirmed boat exploration and fishing features, plus the future map and ownership questions.','Players can explore Nivalis with their own boat and go fishing from the city’s docks and waterways.',[
    ['What boats are confirmed to do','The official feature list ties the player’s own boat directly to city exploration and fishing. Marketing copy presents the docks as a place to retreat when business or story pressure becomes intense.'],
    ['Information still needed','The public materials do not yet confirm boat models, prices, upgrades, docking rules or fast travel. At launch this guide will add the acquisition route, controls, dock locations, route map and any storage or fishing differences.']]],
  ['chess-tournament','Nivalis Nights Chess Tournament','What is known about the high-stakes cyberpunk chess tournament and NPC minigame challenges.','Nivalis Nights includes a chess tournament and allows players to challenge NPCs to minigames. Exact rules, entry steps and rewards have not yet been published.',[
    ['Confirmed activity','The Steam description specifically calls the tournament high stakes, making it a distinct activity worth tracking. It sits alongside business, relationships, home customization, boating and fishing as a way to spend time in the city.'],
    ['Walkthrough plan','Once available, this page will document how to enter, match rules, opponents, bracket or progression, rewards and whether outcomes affect relationships or story choices.']]],
  ['curfew-guide','Nivalis Nights Curfew Guide','How curfew, security systems and illegal actions work according to the official Nivalis Nights feature list.','Curfew creates a risk layer: players can avoid security systems while operating illegally, including sabotaging competitors.',[
    ['Confirmed risk and reward','The feature list contrasts legal ingredient growing with illegal sabotage under curfew. It warns that consequences inflicted on competitors can also happen to the player, indicating reciprocal risk rather than consequence-free actions.'],
    ['Guide boundaries','Exact curfew hours, detection rules, penalties and security routes are not public. A release guide must test them by district and explain safe routing without pretending that pre-release footage reveals final mechanics.']]],
  ['sabotage-guide','Nivalis Nights Sabotage Guide','Confirmed competitor sabotage, curfew risk and the evidence needed for a responsible strategy guide.','Players may sabotage business rivals under cover of curfew, but rival actions or consequences can also affect the player.',[
    ['Where sabotage fits','Sabotage links business competition to the story’s security pressure. The official description frames it as illegal and risky, while the district itself is already under CorpSec crackdowns.'],
    ['What to test','The launch guide will identify prerequisites, targets, security avoidance, possible outcomes, relationship or reputation effects, retaliation and recovery. It will separate repeatable mechanics from one-off quest events.']]],
  ['relationships','Nivalis Nights Relationships','Friendship, enemies, romance and relationship management in the cyberpunk life sim.','Players can forge bonds, make friends and enemies, discover character stories and perhaps find love. Choices are intended to have meaningful effects.',[
    ['More than romance','Official descriptions repeatedly use “relationships” rather than presenting the system only as dating. The cast includes unusual inhabitants, and story interactions are balanced alongside quests, rewards and the economy.'],
    ['Future character evidence','Character pages will state whether a person is a friend, rival or romance option only after confirmation. Schedules, gifts, dialogue choices and event flags must be tested or sourced, with spoilers clearly marked.']]],
  ['story','Nivalis Nights Story','Spoiler-light overview of the confirmed story setup, CorpSec pressure, a serial killer and player choices.','The story begins in a district pushed toward crisis by CorpSec crackdowns and a mysterious serial killer, while the player tries to build a life and business.',[
    ['Story and simulation connect','ION LANDS says major story beats link with gameplay systems and provide rewards. The team adjusted plotlines, quest difficulty and the economy together, and describes the player’s choices as meaningful and resonant.'],
    ['Spoiler policy','This hub will remain a safe overview. Individual story quests and endings will use visible spoiler labels and avoid revealing consequences in titles or meta descriptions.']]],
  ['corpsec','Nivalis Nights CorpSec','What official descriptions reveal about CorpSec, curfew and security pressure in Nivalis Nights.','CorpSec is associated with crackdowns in the game’s troubled district. Players must also avoid security systems when carrying out illegal actions during curfew.',[
    ['Confirmed role','Public material positions CorpSec as part of the city’s pressure and danger rather than merely background decoration. It does not yet confirm leaders, ranks, facilities or whether CorpSec is a joinable faction.'],
    ['Future guide scope','After release, this page will connect confirmed characters, locations, quests, security mechanics and choices. Unnamed figures visible in trailers will not receive invented identities.']]],
  ['languages','Nivalis Nights Languages','All 11 supported Nivalis Nights languages and which one includes full audio.','Steam lists 11 supported languages. English has interface, full audio and subtitles; the other ten listed languages have interface and subtitles.',[
    ['Supported languages','English, French, German, Spanish (Spain), Japanese, Korean, Portuguese (Brazil), Russian, Simplified Chinese, Traditional Chinese and Turkish are listed on Steam. Localization testing includes UI text, voice synchronization and optimized fonts for Chinese, Korean and Japanese.'],
    ['Audio and subtitles','Only English is currently marked for full audio on the storefront. All 11 are marked for interface and subtitles. Storefront fields can change, so players should recheck Steam near launch.']]],
  ['steam-features','Nivalis Nights Steam Features','Confirmed Steam features: single-player, achievements, cloud saves and Family Sharing.','The Nivalis Nights Steam listing currently marks Single-player, Steam Achievements, Steam Cloud and Family Sharing.',[
    ['What the badges mean','Single-player confirms the current play mode. Steam Cloud indicates cloud functionality is planned, and achievements are listed even though their names and conditions are not yet public. Family Sharing availability is also shown.'],
    ['What is not confirmed here','The listing does not currently establish multiplayer, Workshop support, trading cards or Valve’s Steam Deck rating. Separate pages should not imply those features without an official badge or tested release build.']]],
  ['steam-achievements','Nivalis Nights Achievements','Current Steam achievement status and the quality rules for the future achievement guide.','Steam Achievements are confirmed on the store page, but the achievement list, descriptions and unlock conditions are not yet public on that page.',[
    ['Current answer','Achievement support is planned for the September 29 release. There is not yet enough official information to publish one URL per achievement.'],
    ['Launch database standard','Each achievement entry will include the exact name, description, unlock steps, missable status, related quest and spoiler warning. Hidden achievements should not be exposed in page titles without a clear spoiler-safe route.']]],
  ['steam-cloud','Nivalis Nights Steam Cloud','Whether Nivalis Nights supports Steam Cloud and what players should verify at launch.','Yes. Steam Cloud is listed as a feature on the Nivalis Nights store page.',[
    ['What is confirmed','The storefront badge confirms planned cloud functionality, but it does not specify which save and settings files synchronize, storage limits or cross-device conflict behavior.'],
    ['Launch checks','The finished guide will test save upload, multiple PCs, offline-to-online conflicts and whether graphics, controls or accessibility settings travel with the save. Backing up local saves remains sensible until file locations are verified.']]],
  ['single-player','Is Nivalis Nights Single Player?','Nivalis Nights is listed as a single-player game on Steam; here is what that confirms and what it does not.','Yes. Steam marks Nivalis Nights as Single-player. The public listing does not currently show an online co-op or multiplayer feature badge.',[
    ['How the city stays alive','Single-player does not mean the city is static. ION LANDS describes thousands of NPCs with daily schedules, persistent objects, staff activity across districts and relationships that respond to choices.'],
    ['Avoiding unsupported claims','This page reports current storefront features. It does not claim that multiplayer can never be added; it only states that no such mode is currently listed for launch.']]],
];

pages.push(
  ['gameplay-systems','Nivalis Nights Gameplay Systems','Overview of the confirmed daily life, business, ingredient, meal, fishing, boat, home, relationship, minigame, curfew and story systems.','Nivalis Nights combines a daily life simulation with business management, relationships and a persistent cyberpunk city. Players choose how to spend time rather than following one fixed career path.',[
    ['Core progression loops','The player can grow from a noodle stand into restaurants and nightclubs, buy or cultivate ingredients, manage staff activity and compete with rivals. Outside business, confirmed activities include fishing, boat exploration, home decoration, character relationships and a chess tournament.'],
    ['A persistent city','Thousands of NPCs retain schedules across districts and more than 10,000 objects preserve world state. Time of day, realistic weather, curfew security and player choices connect the simulation to story and risk. Exact formulas and unlock orders require release-build evidence.']]],
  ['business-guide','Nivalis Nights Business Strategy Guide','Spoiler-safe overview of the confirmed business ladder, ingredients, meals, staff, rivals, curfew and launch-day testing priorities.','Start with the confirmed business ladder: a noodle stand can lead toward ramen bars, restaurants and nightclubs. Ingredient supply, staffing, time and competitor risk are the key systems to test.',[
    ['Build the supply chain','More than 240 ingredients and 190 meals connect to the food-business layer. Players can buy or grow ingredients, while persistent staff actions can continue across the city. A strong strategy compares ingredient cost, menu value, labor and operating time together.'],
    ['Treat rankings as testable claims','Pre-release material does not reveal startup prices, margins or upgrade effects. After launch, “best business” guides should use controlled operating periods and include purchase cost, staffing, travel, unlock quests and curfew risk rather than ranking venues by their place in marketing copy.']]],
  ['release-date','Nivalis Nights Release Date','Nivalis Nights releases for PC on Steam on September 29, 2026. Check the confirmed date, developer and publisher details.','Nivalis Nights is scheduled to release on Steam on September 29, 2026. It is developed by ION LANDS and published by 505 Games.',[
    ['The confirmed date','The official Steam listing shows September 29, 2026 as both the release date and planned unlock date. ION LANDS also announced that date with the June 2026 name change from Nivalis to Nivalis Nights, clarifying that this is the same game with a new title and logo.'],
    ['What players should do','Wishlist the game on Steam to receive the platform notification. The current listing is for Windows PC; an official release-date trailer says the Epic Games Store version will arrive later, without giving a separate date. This page should be rechecked if either storefront changes.']]],
  ['system-requirements','Nivalis Nights System Requirements','Official minimum and recommended PC requirements for RAM, GPU memory, storage, DirectX, OS and input.','Minimum requirements include 16 GB RAM, a dedicated GPU with at least 6 GB VRAM and 30 GB storage. Recommended graphics use 8 GB VRAM, such as an RTX 2070 or newer, plus an SSD.',[
    ['Minimum PC specification','Steam lists 64-bit Windows 10 or 11, an AMD or Intel CPU, 16 GB RAM, an AMD or NVIDIA dedicated graphics card with at least 6 GB dedicated VRAM, DirectX 11, broadband internet and 30 GB available storage. Controller or keyboard and mouse input is listed.'],
    ['Recommended PC specification','The recommended listing keeps 16 GB RAM and 30 GB storage but calls for an 8 GB dedicated GPU, giving RTX 2070 or newer as an example, DirectX 12 and an SSD. The CPU line is not model-specific, so exact frame-rate predictions would be unreliable before independent benchmarks.']]],
  ['platforms','Nivalis Nights Platforms','Current Nivalis Nights platform status for Steam, Epic Games Store, consoles and Steam Deck.','The confirmed dated release is Windows PC via Steam on September 29, 2026. The official trailer says Epic Games Store will follow later. Console versions are not confirmed on the current official Steam listing.',[
    ['PC storefronts','Steam has the active product page, release date, requirements, languages and feature badges. Epic Games Store is announced for a later date, but no dated Epic page is cited in the current official release material.'],
    ['Console and handheld status','Do not treat PlayStation, Xbox or Nintendo pages from third parties as confirmation unless ION LANDS or 505 Games announces them. Steam lists controller input in the requirements, but controller support and a Valve Steam Deck compatibility rating are different questions.']]],
  ['steam-deck-controller','Nivalis Nights Steam Deck and Controller','Current controller input and Steam Deck verification status for Nivalis Nights.','The PC requirements state “Controller or keyboard + mouse.” The current Steam listing does not display a Valve Verified or Playable rating in the information reviewed for this guide.',[
    ['Controller answer','Both minimum and recommended notes mention controller or keyboard and mouse, so controller input is planned. The storefront does not expose the final button layout, remapping options or whether gameplay can be completed without switching to a pointer.'],
    ['Steam Deck answer','Controller input alone does not prove Steam Deck compatibility. A useful Deck verdict requires Valve’s rating or release-build tests covering performance, text size, launcher behavior, input prompts and battery life. Until then, this page avoids a Verified claim.']]],
  ['languages','Nivalis Nights Languages','The 11 languages listed for Nivalis Nights, with interface, subtitles and English full-audio status.','Steam lists English plus ten translated languages. English includes full audio; all listed languages include interface and subtitles.',[
    ['Complete list','The current storefront lists English, French, German, Spanish from Spain, Japanese, Korean, Brazilian Portuguese, Russian, Simplified Chinese, Traditional Chinese and Turkish. The May developer update says three QA teams and dedicated localization testing are involved.'],
    ['Asian-language support','ION LANDS specifically describes preparing optimized fonts for Chinese, Korean and Japanese before translation updates. Store fields can change close to release, so players looking for a particular dub should distinguish full audio from translated interface and subtitle support.']]],
  ['demo-guide','Does Nivalis Nights Have a Demo?','Current Nivalis Nights demo availability and how to verify any future demo or save transfer support.','The official Steam store page reviewed on July 17, 2026 does not list a downloadable public demo. Wishlist or follow the game for any later announcement.',[
    ['Current status','The product page says the game is not yet available and offers the wishlist action. A demo button or demo package is not shown in the official listing reviewed for this update. This is a current-status answer, not a claim that a demo can never appear.'],
    ['Save transfer','Because no current public demo is listed, there is no official demo-to-full-game save transfer promise to document. If a demo appears, its own announcement or FAQ should be the source for progress limits, availability window and transfer behavior.']]],
  ['price-editions','Nivalis Nights Price and Editions','Current price and edition status for Nivalis Nights on Steam.','The official Steam page reviewed on July 17, 2026 does not display a launch price or multiple editions. The actionable option before release is to wishlist the game.',[
    ['Price status','The storefront provides the date, features, supported languages and PC requirements, but the pre-release purchase box does not yet show a price. Regional launch prices and discounts should not be inferred from third-party key listings.'],
    ['Edition status','No standard-versus-deluxe comparison is available from the official page reviewed here. If 505 Games announces editions, this page should compare included content, cosmetic versus gameplay items, price difference and upgrade paths using the official product details.']]],
  ['fishing-guide','Nivalis Nights Fishing Guide','How fishing works in Nivalis Nights, including visible fish simulation, shoal behavior, bait response and boat exploration.','Fishing is not a hidden random roll. Fish have physical representations, form shoals, react to bait and can be seen in the water before being caught.',[
    ['Physical fish simulation','ION LANDS says hundreds of fish can appear simultaneously and more than 1,000 can be simulated. Each follows other fish or bait, so the salmon a player catches is the same one previously visible in the water. Fish also emit a warm glow.'],
    ['Locations, bait and values','Exact species lists, fishing spots, bait preferences, time windows and sell values are not public in the cited developer update. Those details need release-build testing. The official feature list does confirm that the player can explore by personal boat and go fishing.']]],
  ['romance-guide','Nivalis Nights Romance and Dating Guide','What is confirmed about romance, friendships, enemies and character relationships in Nivalis Nights.','Romance is part of the game: official copy says players may find love, while the broader system includes friendships, enemies and relationship management.',[
    ['Relationship scope','The game asks players to choose between growing a business and forging bonds with inhabitants. Character stories, quests, rewards and choices are designed to interconnect, so relationship guides should cover more than gift lists.'],
    ['No invented romance options','The official material reviewed here does not publish a complete romanceable-character roster, gift preferences or event requirements. Those details will be added by named character only after official confirmation or release-build verification, with spoilers labelled.']]],
  ['money-guide','Nivalis Nights Money and Business Guide','Confirmed ways the Nivalis Nights economy connects businesses, ingredients, meals, fishing and competitors.','The primary announced economic route starts with a noodle stand and grows toward ramen bars, restaurants and nightclubs. Fishing and ingredient supply support the wider life-sim loop.',[
    ['Starting small','Official descriptions repeatedly say the player begins humbly with a noodle or food stand. Players can buy or grow ingredients and spend their days expanding businesses. Exact starting cash, prices and profit margins are not yet public.'],
    ['Reinvestment and risk','The business layer includes staff activity, competitors and illegal sabotage under curfew. A reliable “fastest money” route requires comparable release-build tests of startup cost, operating time, ingredient cost, staffing and upgrades rather than assumptions from the business order.']]],
  ['apartment-decorating','Nivalis Nights Apartments and Decorating','Confirmed home ownership, decoration and furniture systems in Nivalis Nights.','Players can buy and decorate apartments or homes, and can also customize homes for friends. The game includes 620 furniture items according to ION LANDS.',[
    ['Home customization','The official Steam copy treats home decoration as a major low-pressure activity alongside boating, fishing and chess. It refers to multiple homes and customization for friends, although purchase prices and ownership limits are not yet public.'],
    ['Persistent furniture','Developer technology notes describe more than 10,000 persistent world elements, including tables, chairs and dishes, and a major furniture asset polish. Individual item pages need verified acquisition, cost, category and placement details before indexing.']]],
  ['city-guide','Nivalis Nights City and District Guide','Confirmed information about the cyberpunk city of Nivalis, its districts, docks, security and persistent population.','Nivalis is a cyberpunk city stretching from the ocean to the clouds, with districts, docks, businesses, homes, persistent NPC schedules and a realistic weather system.',[
    ['A dense simulated city','ION LANDS says thousands of NPCs continue living their lives. The engine tracks distant district schedules, nearby unseen residents and fully visible characters differently, while more than 10,000 world objects retain their state.'],
    ['Navigation and danger','Players can explore by their own boat, visit docks and move through a district under CorpSec crackdowns. Curfew and security systems add risk. A complete map needs the shipped location names and routes, so this guide does not invent a district list.']]],
  ['day-night-weather','Nivalis Nights Day, Night and Weather','How daily choices, curfew and realistic weather shape the Nivalis Nights simulation.','The game has day and night cycles, a realistic weather system and curfew-related risk. Players decide how to spend each day across business, relationships and other activities.',[
    ['Time management','The official description frames each day as a choice between growing businesses and forming bonds. Steam also tags the game for time management. Exact day length, sleep rules and business opening hours are not yet public.'],
    ['Weather and curfew','The developer says rain and snow effects have been refined. At night, illegal competitor sabotage can occur under curfew, requiring players to avoid security systems. Weather-specific fishing or crop effects still require verification.']]],
  ['beginner-guide','Nivalis Nights Beginner Guide','A spoiler-safe introduction to the confirmed business, relationship, fishing, home, boat and story systems.','Begin by understanding the daily-choice loop: business growth and ingredient supply compete for time with relationships, fishing, boating, decorating and story progress.',[
    ['Choose a focus, not a fantasy build','The official systems suggest several connected paths rather than fixed classes. A noodle stand can lead into larger food and nightlife businesses, while relationships and quests are designed to interact with rewards and the economy.'],
    ['What not to over-plan','Exact profit rankings, best gifts, fish schedules and quest routes are not public before release. Check PC requirements, choose an input method, wishlist the game and use broad system knowledge until tested launch data supports optimization.']]],
  ['best-tips','Nivalis Nights Tips','Useful spoiler-free pre-release tips grounded in confirmed Nivalis Nights systems.','Treat time, ingredient supply and relationships as connected resources. The game lets you specialize, but official descriptions emphasize that daily choices influence business and character progress.',[
    ['Plan around connected systems','Growing ingredients can support food businesses; boating connects exploration and fishing; homes use a large furniture collection; curfew can turn business rivalry into risk. Avoid assuming each activity exists in isolation.'],
    ['Wait for tested rankings','Before release there is no reliable evidence for the best meal, fish, business or upgrade. Once the game launches, comparisons should use consistent time periods and include startup costs, staffing, travel and unlock requirements.']]],
  ['known-issues','Nivalis Nights Known Issues and Patch Notes','Current pre-release issue status and the future versioned troubleshooting policy.','Nivalis Nights has not released yet, so there is no public launch-build issue list. ION LANDS says it is optimizing performance and testing stability, saves, quests, UI, localization and compatibility.',[
    ['Pre-release optimization work','The May update details LODs, light-probe optimization, NPC object pooling, reduced allocations and loading improvements. QA teams test general stability, save/load, quest progression, environments, characters, UI, memory and performance.'],
    ['How issues will be documented','After launch, each issue needs a game version, affected platform or hardware, reproduction steps, workaround and official status. Old workarounds must remain tied to their version so fixed problems do not continue ranking as current advice.']]],
  ['checklists','Nivalis Nights Checklists','Spoiler-safe preparation and launch verification checklists for players and completionists.','Before launch, check the date, PC requirements, language and input support. After launch, collection checklists will cover only verified quests, ingredients, meals, furniture and other entities.',[
    ['Pre-release checklist','Confirm Windows 10/11 64-bit, 16 GB RAM, dedicated GPU memory and 30 GB free space; prefer an SSD for the recommended setup. Check that your chosen language and input method are listed, then wishlist the Steam release.'],
    ['Completion checklist policy','The developers report 100+ quests, 240+ ingredients, 190 meals and 620 furniture items. Those counts justify future checklists, but completion percentages require exact release-build inventories rather than empty boxes or invented names.']]],
  ['faq','Nivalis Nights FAQ','Quick answers about the release date, platform, game type, businesses, fishing, romance, languages and PC requirements.','Nivalis Nights is a single-player cyberpunk life sim releasing on Steam on September 29, 2026, with business management, relationships, fishing, boating, homes, minigames and story choices.',[
    ['Who makes Nivalis Nights?','ION LANDS develops the game and 505 Games publishes it. It was previously promoted as Nivalis; the developer says Nivalis Nights is the same game with a new title and logo.'],
    ['How large is the content?','A May 2026 development update reports more than 100 quests, over 240 ingredients, 190 meals and 620 furniture items. The city also simulates thousands of NPCs, but only named, useful entities should become guide pages.']]],
  ['nivalis-vs-nivalis-nights','Nivalis vs Nivalis Nights','Why the game formerly called Nivalis is now named Nivalis Nights.','Nivalis Nights is the same ION LANDS game previously called Nivalis. The developer announced the new title and logo on June 30, 2026 after resolving a legal matter.',[
    ['What changed','ION LANDS says marketing had been paused while it handled a legal matter with a third party. Once resolved, the team announced the fresh title, logo and September 29, 2026 release date. The underlying game did not become a sequel or separate project.'],
    ['How to read older information','Older trailers, store links and discussions may still use Nivalis. They can remain relevant when they refer to Steam app 1488490 or the same ION LANDS project, but dates and features should be rechecked against current official pages.']]],
  ['about','About Nivalis Nights Wiki','Editorial standards, sourcing and independence information for Nivalis Nights Wiki.','Nivalis Nights Wiki is an independent, unofficial English player resource. It is not affiliated with ION LANDS or 505 Games.',[
    ['Editorial policy','Pre-release claims are sourced to official storefronts and developer updates. After release, exact guides can also use reproducible first-hand testing. Speculation, placeholder entity pages and fabricated names are excluded from the sitemap.'],
    ['Corrections and spoilers','Time-sensitive answers show a review date. Story choices and endings receive spoiler warnings, while corrections should update both the page and its source record. Trademarks and game assets remain the property of their respective owners.']]]
);

const cards={
  guides:[['/release-date/','Release date','September 29, 2026 on Steam'],['/system-requirements/','PC requirements','16 GB RAM and 30 GB storage'],['/businesses/','Businesses','Restaurants, ramen bars and nightclubs'],['/fish/','Fishing','Physical fish simulation'],['/relationships/','Relationships','Friends, enemies and romance'],['/curfew-guide/','Curfew','Security and risk']],
  databases:[['/quests/','100+ quests','Walkthrough hub'],['/ingredients/','240+ ingredients','Sources and recipe uses'],['/meals/','190 meals','Recipes and business value'],['/furniture/','620 furniture items','Acquisition and placement'],['/characters/','Characters','Schedules and relationships'],['/locations/','Locations','District maps and services']],
  businesses:[['/restaurant-management/','Restaurants','Management and profit testing'],['/ramen-bar-guide/','Ramen bars','Ingredients, menus and staffing'],['/nightclub-guide/','Nightclubs','Late-game nightlife business'],['/growing-ingredients/','Growing ingredients','Supply your food venues'],['/sabotage-guide/','Sabotage','Competitors and retaliation'],['/curfew-guide/','Curfew','Avoid security systems']],
};

function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function render(slug,title,description,answer,sections){
 const url=`${domain}/${slug}/`;
 const cardset=cards[slug]||[['/guides/','All guides','Browse confirmed gameplay guides'],['/databases/','Databases','Quests, items, meals and furniture'],['/faq/','FAQ','Quick pre-release answers']];
 const sectionHtml=sections.map(([h,b])=>`<section class="panel"><h2>${esc(h)}</h2><p>${esc(b)}</p></section>`).join('\n');
 const cardHtml=cardset.map(([u,h,b])=>`<a class="card" href="${u}"><strong>${esc(h)}</strong><span>${esc(b)}</span></a>`).join('');
 const schema=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:title,description,mainEntityOfPage:url,datePublished:updated,dateModified:updated,author:{'@type':'Organization',name:'Nivalis Nights Wiki'},publisher:{'@type':'Organization',name:'Nivalis Nights Wiki'}});
 const crumbs=JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${domain}/`},{'@type':'ListItem',position:2,name:title,item:url}]});
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Guide & Confirmed Details</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1488490/header.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${schema}</script><script type="application/ld+json">${crumbs}</script></head><body><header class="top"><nav class="nav wrap" aria-label="Main navigation"><a href="/">Nivalis Nights Wiki</a><a href="/guides/">Guides</a><a href="/databases/">Databases</a><a href="/businesses/">Businesses</a><a href="/characters/">Characters</a><a href="/quests/">Quests</a><a href="/faq/">FAQ</a></nav></header><main class="wrap"><div class="crumb"><a href="/">Home</a> / ${esc(title)}</div><h1>${esc(title)}</h1><p class="lede">${esc(description)}</p><div class="answer"><strong>Quick answer:</strong> ${esc(answer)}</div>${sectionHtml}<section><h2>Related Nivalis Nights guides</h2><div class="cards">${cardHtml}</div></section><section class="panel source"><h2>Sources and verification</h2><p>This pre-release page uses the official <a href="${steam}" rel="nofollow">Nivalis Nights Steam listing</a> and the developer’s <a href="${devlog}" rel="nofollow">Steam news and development updates</a>. Exact values and entity names will be added only when officially published or verified in the release build.</p></section><p class="updated">Last reviewed: July 17, 2026 · Independent, unofficial player guide.</p></main><footer class="footer"><div class="wrap">Nivalis Nights Wiki is an independent fan resource and is not affiliated with ION LANDS or 505 Games.</div></footer></body></html>`;
}

for(const p of pages){const dir=path.join(root,p[0]);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),render(...p));}
const urls=['/'];
for(const e of fs.readdirSync(root,{withFileTypes:true})){
  if(e.isDirectory()&&fs.existsSync(path.join(root,e.name,'index.html')))urls.push(`/${e.name}/`);
}
urls.sort((a,b)=>a==='/'?-1:b==='/'?1:a.localeCompare(b));
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${domain}${u}</loc><lastmod>${updated}</lastmod></url>`).join('\n')}\n</urlset>\n`;
fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);
console.log(`Generated ${new Set(pages.map(p=>p[0])).size} verified pages and a ${urls.length}-URL sitemap.`);
